### ISSUE TITLE
请求网络时的一个异常，但不会影响网络请求

### ISSUE THREAD

**Issue by 364089999** [yanzhenjie/NoHttp#120]
java.text.ParseException: Unparseable date: "-1" (at offset 0)
	    at java.text.DateFormat.parse(DateFormat.java:579)
            at com.yanzhenjie.nohttp.tools.HeaderUtils.parseGMTToMillis(HeaderUtils.java:61)
            at com.yanzhenjie.nohttp.Headers.getDateField(Headers.java:480)
            at com.yanzhenjie.nohttp.Headers.getExpiration(Headers.java:432)
            at com.yanzhenjie.nohttp.tools.HeaderUtils.getLocalExpires(HeaderUtils.java:150)
            at com.yanzhenjie.nohttp.rest.RestProtocol.analysisCacheAndProtocol(RestProtocol.java:216)
            at com.yanzhenjie.nohttp.rest.RestProtocol.request(RestProtocol.java:60)
            at com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:41)
            at com.yanzhenjie.nohttp.NoHttp.startRequestSync(NoHttp.java:335)

**Comment by yanzhenjie** [comment]
是服务器返回的一个Header有问题，不用管。新版应该不会打印这个警告了。
