### ISSUE TITLE
手动终止下载，导致NoHttp内部报错java.io.InterruptedIOException

### ISSUE THREAD

**Issue by fairytale110** [yanzhenjie/NoHttp#123]
文件正在下载中，手动调用` CallServer.getDownloadInstance().stop();` 报错：
`java.io.InterruptedIOException
                                                            at okhttp3.internal.huc.OkHttpURLConnection.getResponse(OkHttpURLConnection.java:430)
                                                            at okhttp3.internal.huc.OkHttpURLConnection.getResponseCode(OkHttpURLConnection.java:473)
                                                            at com.yanzhenjie.nohttp.OkHttpNetwork.getResponseCode(OkHttpNetwork.java:45)
                                                            at com.yanzhenjie.nohttp.HttpConnection.getConnection(HttpConnection.java:75)
                                                            at com.yanzhenjie.nohttp.download.Downloader.download(Downloader.java:122)
                                                            at com.yanzhenjie.nohttp.download.SyncDownloadExecutor.execute(SyncDownloadExecutor.java:41)
                                                            at com.yanzhenjie.nohttp.download.DownloadDispatcher.run(DownloadDispatcher.java:93)`

导致我的app崩溃了，，，，

**Comment by yanzhenjie** [comment]
在这里又抓异常的，但是这个底层的没抓到。在停止队列前，应该先取消所有的下载任务，`queue.cancelAll();`，然后再`queue.stop();`。
