### ISSUE TITLE
Android 4.1.1 异步下载报错

### ISSUE THREAD

**Issue by fairytale110** [yanzhenjie/NoHttp#131]
java.io.InterruptedIOException
                                                  at okhttp3.internal.huc.OkHttpURLConnection.getResponse(OkHttpURLConnection.java:430)
                                                  at okhttp3.internal.huc.OkHttpURLConnection.getResponseCode(OkHttpURLConnection.java:473)
                                                  at com.yanzhenjie.nohttp.OkHttpNetwork.getResponseCode(OkHttpNetwork.java:45)
                                                  at com.yanzhenjie.nohttp.HttpConnection.getConnection(HttpConnection.java:79)
                                                  at com.yanzhenjie.nohttp.download.Downloader.getConnectionRetry(Downloader.java:83)
                                                  at com.yanzhenjie.nohttp.download.Downloader.download(Downloader.java:191)
                                                  at com.yanzhenjie.nohttp.download.SyncDownloadExecutor.execute(SyncDownloadExecutor.java:42)
                                                  at com.yanzhenjie.nohttp.download.DownloadDispatcher.run(DownloadDispatcher.java:86)

**Comment by fairytale110** [comment]
同样的操作在Android 7.1上面能正常下载，但是在Android 4.1.1上面就报上面的错，可以确定是下载模块的问题，希望可以优化下

**Comment by yanzhenjie** [comment]
io中断是服务器或者网络的问题，你可以明确指定okhttp的版本为3.9.0再试试。
