### ISSUE TITLE
初始化问题

### ISSUE THREAD

**Issue by RuffianZhong** [yanzhenjie/NoHttp#134]
Please invoke NoHttp.initialize(Application) on Application#onCreate()

一定要在Application#onCreate() 中做初始化吗？现在有一个需求想要在Activity中初始化可以实现吗？

**Comment by yanzhenjie** [comment]
可以在任何地方初始化，只要有cotext就可以。但是在其它地方初始化不安全。

**Comment by RuffianZhong** [comment]
@yanzhenjie 
我使用的是高级初始化，做一个小SDK，觉得你这个框架很轻量，因为我SDK的初始化是必须放在Activity中，如果可以的话，我想如果NoHttp 的高级初始化也能放在Activity中就好了，但是发现会报错
` java.lang.ExceptionInInitializerError: Please invoke NoHttp.initialize(Application) on Application#onCreate()
                                                     at com.yanzhenjie.nohttp.NoHttp.testInitialize(NoHttp.java:98)
                                                     at com.yanzhenjie.nohttp.NoHttp.getInitializeConfig(NoHttp.java:113)
                                                     at com.yanzhenjie.nohttp.BasicRequest.<init>(BasicRequest.java:92)
                                                     at com.yanzhenjie.nohttp.rest.ProtocolRequest.<init>(ProtocolRequest.java:57)
                                                     at com.yanzhenjie.nohttp.rest.Request.<init>(Request.java:45)
                                                     at com.yanzhenjie.nohttp.rest.RestRequest.<init>(RestRequest.java:61)
                                                     at com.yanzhenjie.nohttp.rest.JsonObjectRequest.<init>(JsonObjectRequest.java:36)`

**Comment by yanzhenjie** [comment]
这个错是没初始化的问题，你只要保证初始化这个方法被调用就好了。

**Comment by RuffianZhong** [comment]
@yanzhenjie 
抱歉，我的错，我的错。
只要初始化之后应该就能正常使用了哦？

**Comment by yanzhenjie** [comment]
是的，只要有context就能正常工作。
