### ISSUE TITLE
使用1.1版本的时候，友盟log中出现的错误BasicMultiValueMap.add时候报空指针异常

### ISSUE THREAD

**Issue by qiulei19850103** [yanzhenjie/NoHttp#137]
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
	at com.yanzhenjie.nohttp.tools.BasicMultiValueMap.add(BasicMultiValueMap.java:41)
	at com.yanzhenjie.nohttp.tools.BasicMultiValueMap.add(BasicMultiValueMap.java:48)
	at com.yanzhenjie.nohttp.tools.BasicMultiValueMap.set(BasicMultiValueMap.java:61)
	at com.yanzhenjie.nohttp.HttpHeaders.setAll(HttpHeaders.java:76)
	at com.yanzhenjie.nohttp.rest.RestProtocol.analysisCacheAndProtocol(RestProtocol.java:232)
	at com.yanzhenjie.nohttp.rest.RestProtocol.request(RestProtocol.java:60)
	at com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:41)
	at com.yanzhenjie.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:104)

**Comment by xicong** [comment]
我也发现这个问题了         java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
                                                                       at com.yanzhenjie.nohttp.tools.BasicMultiValueMap.add(BasicMultiValueMap.java:41)
                                                                       at com.yanzhenjie.nohttp.tools.BasicMultiValueMap.add(BasicMultiValueMap.java:48)
                                                                       at com.yanzhenjie.nohttp.tools.BasicMultiValueMap.set(BasicMultiValueMap.java:61)
                                                                       at com.yanzhenjie.nohttp.Headers.setAll(Headers.java:229)
                                                                       at com.yanzhenjie.nohttp.rest.RestProtocol.analysisCacheAndProtocol(RestProtocol.java:231)
                                                                       at com.yanzhenjie.nohttp.rest.RestProtocol.request(RestProtocol.java:60)
                                                                       at com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:41)
                                                                       at com.yanzhenjie.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:96)

**Comment by yanzhenjie** [comment]
确定有这个问题，汇总到 #147

**Comment by xicong** [comment]
好多人反馈哦，什么时候可以更新啊

**Comment by yanzhenjie** [comment]
不是更新了1.1.5嘛。

**Comment by xicong** [comment]
嗯嗯，看到了，大佬辛苦了
