### ISSUE TITLE
Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by xicong** [yanzhenjie/NoHttp#139]
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
                                                                       at com.yanzhenjie.nohttp.tools.BasicMultiValueMap.add(BasicMultiValueMap.java:41)
                                                                       at com.yanzhenjie.nohttp.tools.BasicMultiValueMap.add(BasicMultiValueMap.java:48)
                                                                       at com.yanzhenjie.nohttp.tools.BasicMultiValueMap.set(BasicMultiValueMap.java:61)
                                                                       at com.yanzhenjie.nohttp.Headers.setAll(Headers.java:229)
                                                                       at com.yanzhenjie.nohttp.rest.RestProtocol.analysisCacheAndProtocol(RestProtocol.java:231)
                                                                       at com.yanzhenjie.nohttp.rest.RestProtocol.request(RestProtocol.java:60)
                                                                       at com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:41)
                                                                       at com.yanzhenjie.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:96)

**Comment by yanzhenjie** [comment]
#147
