### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by animus198656** [yanzhenjie/NoHttp#141]
java.lang.OutOfMemoryError
	at java.util.zip.Inflater.inflateImpl(Inflater.java)
	at java.util.zip.Inflater.inflate(Inflater.java:237)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:140)
	at java.io.InputStream.read(InputStream.java:162)
	at com.yanzhenjie.nohttp.tools.IOUtils.a(IOUtils.java)
	at com.yanzhenjie.nohttp.tools.IOUtils.a(IOUtils.java)
	at com.yanzhenjie.nohttp.rest.RestProtocol.a(RestProtocol.java)
	at com.yanzhenjie.nohttp.rest.RestProtocol.a(RestProtocol.java)
	at com.yanzhenjie.nohttp.rest.RestProtocol.a(RestProtocol.java)
	at com.yanzhenjie.nohttp.rest.SyncRequestExecutor.a(SyncRequestExecutor.java)
	at com.yanzhenjie.nohttp.NoHttp.a(NoHttp.java)
	at com.qudu.commlibrary.nohttp.RxNoHttp$4.a(RxNoHttp.java)
	at com.qudu.commlibrary.nohttp.RxNoHttp$4.a(RxNoHttp.java)
	at rx.Observable.a(Observable.java)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.c(OperatorSubscribeOn.java)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.c(CachedThreadScheduler.java)
	... 8 more

**Comment by yanzhenjie** [comment]
服务器返回的content太大了吧。
