### ISSUE TITLE
在小米4.2.2手机上崩溃

### ISSUE THREAD

**Issue by MrGeLong** [yanzhenjie/NoHttp#144]
错误日志
java.lang.IllegalArgumentException: SSLSocketFactory is null

at javax.net.ssl.HttpsURLConnection.setSSLSocketFactory(HttpsURLConnection.java:282)

at com.sina.weibo.sdk.net.ConnectionFactory.createConnect(ConnectionFactory.java:50)

at com.sina.weibo.sdk.net.HttpManager.requestHttpExecute(HttpManager.java:76)

at com.sina.weibo.sdk.net.HttpManager.openUrl(HttpManager.java:63)

at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:400)

at com.sina.weibo.sdk.utils.AidTask.access$200(AidTask.java:49)

at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:232)

at java.lang.Thread.run(Thread.java:856)，这应该怎么解决啊

**Comment by yanzhenjie** [comment]
新浪微博SDK的吧。
