### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by xicong** [yanzhenjie/NoHttp#147]
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
at com.yanzhenjie.nohttp.tools.BasicMultiValueMap.add(BasicMultiValueMap.java:41)
at com.yanzhenjie.nohttp.tools.BasicMultiValueMap.add(BasicMultiValueMap.java:48)
at com.yanzhenjie.nohttp.tools.BasicMultiValueMap.set(BasicMultiValueMap.java:61)
at com.yanzhenjie.nohttp.Headers.setAll(Headers.java:229)
at com.yanzhenjie.nohttp.rest.RestProtocol.analysisCacheAndProtocol(RestProtocol.java:231)
at com.yanzhenjie.nohttp.rest.RestProtocol.request(RestProtocol.java:60)
at com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:41)
at com.yanzhenjie.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:96)

**Comment by xicong** [comment]
怎么不更新了啊

**Comment by yanzhenjie** [comment]
发布了1.1.5，修复了该问题，大家试试新版吧，谢谢大家的反馈！  
我更希望的是以后发现问题，大家伙儿改了提交个PR，我合并下发布新版就好了，最近太忙了，好几个库都没时间更，想法是有的。
