### ISSUE TITLE
求教，运行过段时间就提示无法连接到网络，网络没问题，xutils用起来不会出现这种情况

### ISSUE THREAD

**Issue by yunlong0616** [yanzhenjie/NoHttp#150]
12-19 11:10:00.505 23838-24102/? D/NoHttpSample: --------------Request start--------------
12-19 11:10:00.508 23838-24102/? E/NoHttpSample: com.yolanda.nohttp.error.NetworkError: The network is not available, please check the network. The requested url is: (url地址)
                                                     at com.yolanda.nohttp.HttpConnection.getConnection(HttpConnection.java:69)
                                                     at com.yolanda.nohttp.rest.RestProtocol.getHttpResponse(RestProtocol.java:118)
                                                     at com.yolanda.nohttp.rest.RestProtocol.requestNetwork(RestProtocol.java:82)
                                                     at com.yolanda.nohttp.rest.RestParser.parserRequest(RestParser.java:44)
                                                     at com.yolanda.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:41)
                                                     at com.yolanda.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:94)
12-19 11:10:00.508 23838-24102/? D/NoHttpSample: --------------Request finish--------------

**Comment by yanzhenjie** [comment]
发布了1.1.5，你再试试新版。

**Comment by yuzhongxingke** [comment]
@yunlong0616 请问你这个问题解决没有？我也遇到这种情况，请求一次，然后等会一会再请求就会各种超时

**Comment by yuzhongxingke** [comment]
@yunlong0616 我使用的版本是1.1.8，也是不行的，之前1.0.4倒没这个问题，请问哪个版本可以用呢？

**Comment by yanzhenjie** [comment]
昨天发布了1.1.9，优化了网络检查这一块，如果还在使用的同学麻烦升级一下，应该即可，多谢大家的反馈。
