### ISSUE TITLE
出现闪退问题， java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.yanzhenjie.nohttp.rest.Request.isCanceled()' on a null object reference

### ISSUE THREAD

**Issue by richfuns** [yanzhenjie/NoHttp#164]
`E/AndroidRuntime: FATAL EXCEPTION: pool-5-thread-2
                                                                     Process: com.niucha.zuoy, PID: 21139
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.yanzhenjie.nohttp.rest.Request.isCanceled()' on a null object reference
                                                                         at com.yanzhenjie.nohttp.rest.AsyncRequestExecutor$RequestTask.run(AsyncRequestExecutor.java:58)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)`

**Comment by yanzhenjie** [comment]
看错误应该是你传了一个null request进去。

**Comment by richfuns** [comment]
@yanzhenjie 这个是我的问题，不好意思
