### ISSUE TITLE
1.1.9版本空指针问题，频繁出现

### ISSUE THREAD

**Issue by MrXieP** [yanzhenjie/NoHttp#166]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.yanzhenjie.nohttp.rest.Request.cancelBySign(java.lang.Object)' on a null object reference
	at com.yanzhenjie.nohttp.rest.RequestQueue.cancelBySign(RequestQueue.java:114)
	at com.easyxiu.mywucar.net.CallServer.cancelRequest(CallServer.java:64)
	at com.easyxiu.mywucar.net.HttpsUtils.cancelRequest(HttpsUtils.java:105)
	at com.easyxiu.mywucar.ui.BaseActivity.onDestroy(BaseActivity.java:185)
	at com.easyxiu.mywucar.order.BaseOrderActivity.onDestroy(BaseOrderActivity.java:152)
	at com.easyxiu.mywucar.order.WashOrderActivity.onDestroy(WashOrderActivity.java:1599)
	at android.app.Activity.performDestroy(Activity.java:6456)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
	at android.app.ActivityThread.access$1500(ActivityThread.java:150)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by hushengjun** [comment]
我也发生过这个问题，但不是很频繁，有一定几率
