### ISSUE TITLE
thread interrupted错误

### ISSUE THREAD

**Issue by BBBOND** [yanzhenjie/NoHttp#17]
android 6.0 RequestQueue 去 start() 一个 stringRequest 时，报thread interrupted无法连接上网络，能帮忙分析一下错误吗？

```
java.io.InterruptedIOException: thread interrupted
at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
at com.android.okhttp.okio.Okio$1.write(Okio.java:73)
at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:52)
at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:903)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:789)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
at com.yolanda.nohttp.BasicConnection.getConnection(BasicConnection.java:88)
at com.yolanda.nohttp.rest.HttpRestConnection.sendRequestHandleRetry(HttpRestConnection.java:135)
at com.yolanda.nohttp.rest.HttpRestConnection.requestNetwork(HttpRestConnection.java:84)
at com.yolanda.nohttp.rest.HttpRestParser.parserRequest(HttpRestParser.java:51)
at com.yolanda.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:101)
```

**Comment by BBBOND** [comment]
在android 5.0.2上能正常使用

**Comment by yanzhenjie** [comment]
@BBBOND 最好就是下载demo，把demo中的某个连接换成你的连接测试下

**Comment by yuanshenbin** [comment]
老严，我也遇到这个错了，网络很差的情况下出现的
