### ISSUE TITLE
java.net.SocketException: sendto failed: EPIPE (Broken pipe)

### ISSUE THREAD

**Issue by yanzhenjie** [yanzhenjie/NoHttp#42]
```
java.net.SocketException: sendto failed: EPIPE (Broken pipe)
at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
at libcore.io.IoBridge.sendto(IoBridge.java:515)
at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504)
at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
at okio.Okio$1.write(Okio.java:78)
...
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:818) 
```

`sendto failed: EPIPE (Broken pipe)`，swankjesse的回答：That's working as designed. Sometimes you lose network connectivity.

Please see here: [https://github.com/square/okhttp/issues/1775](https://github.com/square/okhttp/issues/1775)

**Comment by yanzhenjie** [comment]
这个一般是服务器限制了传文件的大小，当一个文件上传达到一定的大小时，服务器不接受传输了，网络连接断开了，客户端不知道，继续发送数据的时候就会报这个错。可以从以下几个方面判断：
1. 网络是否稳定。
2. 服务器的tomcat、apache、iis等服务器软件是否限制了上传body的大小。服务端开发人员是限制了单个文件的大小，你的单个文件是否太大了。
3. 服务器是否开启了上传文件会超时的设置，例如tomcat下就以后这个设置。
