### ISSUE TITLE
小米5手机4G环境下数据失败，wifi环境下数据获取正常

### ISSUE THREAD

**Issue by xiaoxiongtest** [yanzhenjie/NoHttp#80]
小米5手机4G环境下数据失败，wifi环境下数据获取正常
java.net.URISyntaxException:Malformed escape pair at index 250:
	at java.net.URI$Parser.fail(URI.java:2856)
	at java.net.URI$Parser.sacnEscape(URI.java:2986)
	at java.net.URI$Parser.sacn(URI.java:3009)
	at java.net.URI$Parser.checkChars(URI.java:3027)
	at java.net.URI$Parser.parseHierarchical(URI.java:3119)
	at java.net.URI$Parser.parse(URI.java:3061)
	at java.net.URI.<int>(URI.java:590)
	at com.yanzhenjie.nohttp.HttpConnection.createNetwork(HttpConnection.java:164)
	at com.yanzhenjie.nohttp.HttpConnection.createConnectionAndWriteData(HttpConnection.java:118)
	at com.yanzhenjie.nohttp.HttpConnection.getConnection(HttpConnection.java:73)
	at com.yanzhenjie.nohttp.rest.RestProtocol.getHttpProtocol(RestProtocol.jva:161)
	at com.yanzhenjie.nohttp.rest.RestProtocol.requestCacheOrNetwork(RestProtocol.jva:123)
	at com.yanzhenjie.nohttp.rest.RestProtocol.request(RestProtocol.jva:59)

**Comment by weilixing00** [comment]
是不是连的你们公司局域网？

**Comment by xiaoxiongtest** [comment]
不是，是线上正式环境，而且vivox9手机也出现相同的问题

**Comment by xiaoxiongtest** [comment]
问题解决了，因为请求地址中参数中有“：”字符！
