### ISSUE TITLE
在Fragment中使用 第一次请求总是失败

### ISSUE THREAD

**Issue by pluszhou** [yanzhenjie/NoHttp#81]
03-17 15:14:09.743 17844-17865/com.besonit.communicationviewer E/NoHttpSample: java.io.EOFException
                                                                                   at libcore.io.Streams.readAsciiLine(Streams.java:203)
                                                                                   at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:573)
                                                                                   at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:821)
                                                                                   at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
                                                                                   at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:495)
                                                                                   at com.yolanda.nohttp.URLConnectionNetworkExecutor$DefaultNetwork.getResponseCode(URLConnectionNetworkExecutor.java:134)
                                                                                   at com.yolanda.nohttp.HttpConnection.getConnection(HttpConnection.java:74)
                                                                                   at com.yolanda.nohttp.rest.RestProtocol.getHttpResponse(RestProtocol.java:118)
                                                                                   at com.yolanda.nohttp.rest.RestProtocol.requestNetwork(RestProtocol.java:82)
                                                                                   at com.yolanda.nohttp.rest.RestParser.parserRequest(RestParser.java:44)
                                                                                   at com.yolanda.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:41)
                                                                                   at com.yolanda.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:94)
03-17 15:14:09.743 17844-17844/com.besonit.communicationviewer E/NoHttpSample: 错误：null

**Comment by yanzhenjie** [comment]
一般是网络和服务器不稳定造成，建议你把底层切换为okhttp的试试，应该就没问题了。

**Comment by pluszhou** [comment]
但是切换为ok时   不能添加多个请求头,

**Comment by yanzhenjie** [comment]
你不是新开了一个Issue嘛。
