### ISSUE TITLE
Galaxy Nexus 4.1.1手机在app内静置一两分钟左右，就会出现这个用的URLConnectionNetworkExecutor，如果底层库配置成okhttp，那么cm14等少数国产手机,okhttp又有https://github.com/square/okhttp/issues/3164这个bug

### ISSUE THREAD

**Issue by feb07** [yanzhenjie/NoHttp#84]
com.besonit.communicationviewer E/NoHttpSample: java.io.EOFException
at libcore.io.Streams.readAsciiLine(Streams.java:203)
at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:573)
at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:821)
at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:495)
at com.yolanda.nohttp.URLConnectionNetworkExecutor$DefaultNetwork.getResponseCode(URLConnectionNetworkExecutor.java:134)
at com.yolanda.nohttp.HttpConnection.getConnection(HttpConnection.java:74)
at com.yolanda.nohttp.rest.RestProtocol.getHttpResponse(RestProtocol.java:118)
at com.yolanda.nohttp.rest.RestProtocol.requestNetwork(RestProtocol.java:82)
at com.yolanda.nohttp.rest.RestParser.parserRequest(RestParser.java:44)
at com.yolanda.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:41)
at com.yolanda.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:94)
03-17 15:14:09.743 17844-17844/com.besonit.communicationviewer E/NoHttpSample: 错误：null

**Comment by feb07** [comment]
okhttp又有https://github.com/square/okhttp/issues/3164这个问题
