### ISSUE TITLE
执行网络请求时报内存溢出了

### ISSUE THREAD

**Issue by qiulei19850103** [yanzhenjie/NoHttp#87]
java.lang.OutOfMemoryError: Could not allocate JNI Env
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:1063)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
	at okhttp3.Dispatcher.enqueue(Dispatcher.java:129)
	at okhttp3.RealCall.enqueue(RealCall.java:78)
	at okhttp3.internal.huc.OkHttpURLConnection.connect(OkHttpURLConnection.java:125)
	at okhttp3.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at okhttp3.internal.huc.OkHttpsURLConnection.connect(OkHttpsURLConnection.java:26)
	at com.yanzhenjie.nohttp.OkHttpNetworkExecutor.execute(OkHttpNetworkExecutor.java:82)
	at com.yolanda.nohttp.HttpConnection.createNetwork(HttpConnection.java:163)
	at com.yolanda.nohttp.HttpConnection.createConnectionAndWriteData(HttpConnection.java:117)
	at com.yolanda.nohttp.HttpConnection.getConnection(HttpConnection.java:72)
	at com.yolanda.nohttp.rest.RestProtocol.getHttpResponse(RestProtocol.java:118)
	at com.yolanda.nohttp.rest.RestProtocol.requestNetwork(RestProtocol.java:74)
	at com.yolanda.nohttp.rest.RestParser.parserRequest(RestParser.java:44)
	at com.yolanda.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:41)
	at com.yolanda.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:94)

**Comment by yanzhenjie** [comment]
底层内存移除，无法控制，第一，你是不是建立了多个请求队列没有退出。第二，你可以把底层换为OkHttp，看你使用的是HttpURLConnection。

**Comment by qiulei19850103** [comment]
我是直接拿你demo直接使用的，一个是请求队列，一个是下载队列，现在只使用了请求队列。第二，是根据你demo中的代码配置的OKHttp.现在在统计反馈的crash中，这个问题还是蛮多的。

**Comment by yanzhenjie** [comment]
根据堆栈信息，你使用的是HttpURLConnection。直接使用demo是说只是运行了一下demo吗？

**Comment by yanzhenjie** [comment]
非常抱歉，我现在回头预览Issue，发现我之前看错了堆栈信息，这个问题我在我们的统计中没有发现过，其它开发者也没反馈过。看堆栈信息okhttp底层反馈出来的，我今天会把升级NoHttp使用的OkHttp到3.7.0版本。
