### ISSUE TITLE
华为P7 EMUI3.1在使用下载时报错

### ISSUE THREAD

**Issue by poorgod** [yanzhenjie/NoHttp#89]
04-21 20:35:09.590 14776-15087/com.yanzhenjie.nohttp.sample E/NoHttpSample: java.lang.ArithmeticException: divide by zero
at com.yanzhenjie.nohttp.download.Downloader.download(Downloader.java:250)
at com.yanzhenjie.nohttp.download.SyncDownloadExecutor.execute(SyncDownloadExecutor.java:41)
at com.yanzhenjie.nohttp.download.DownloadDispatcher.run(DownloadDispatcher.java:93)
计算下载速度时，时间差为0了

**Comment by yanzhenjie** [comment]
我正在修复，发布后通知你，谢谢反馈。
