### ISSUE TITLE
使用StrictMode测试出的问题

### ISSUE THREAD

**Issue by qiulei19850103** [yanzhenjie/NoHttp#95]
StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                               java.lang.Throwable: Explicit termination method 'response.body().close()' not called
                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at okhttp3.internal.platform.AndroidPlatform$CloseGuard.createAndOpen(AndroidPlatform.java:272)
                                                   at okhttp3.internal.platform.AndroidPlatform.getStackTraceForCloseable(AndroidPlatform.java:138)
                                                   at okhttp3.RealCall.captureCallStackTrace(RealCall.java:72)
                                                   at okhttp3.RealCall.enqueue(RealCall.java:81)
                                                   at okhttp3.internal.huc.OkHttpURLConnection.connect(OkHttpURLConnection.java:124)
                                                   at com.yanzhenjie.nohttp.OkHttpNetworkExecutor.execute(OkHttpNetworkExecutor.java:75)
                                                   at com.yanzhenjie.nohttp.HttpConnection.createNetwork(HttpConnection.java:165)
                                                   at com.yanzhenjie.nohttp.HttpConnection.createConnectionAndWriteData(HttpConnection.java:118)
                                                   at com.yanzhenjie.nohttp.HttpConnection.getConnection(HttpConnection.java:73)
                                                   at com.yanzhenjie.nohttp.HttpConnection.handleRedirect(HttpConnection.java:223)
                                                   at com.yanzhenjie.nohttp.HttpConnection.getConnection(HttpConnection.java:80)
                                                   at com.yanzhenjie.nohttp.HttpConnection.handleRedirect(HttpConnection.java:223)
                                                   at com.yanzhenjie.nohttp.HttpConnection.getConnection(HttpConnection.java:80)
                                                   at com.yanzhenjie.nohttp.rest.RestProtocol.getHttpProtocol(RestProtocol.java:161)
                                                   at com.yanzhenjie.nohttp.rest.RestProtocol.requestCacheOrNetwork(RestProtocol.java:105)
                                                   at com.yanzhenjie.nohttp.rest.RestProtocol.request(RestProtocol.java:59)
                                                   at com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:41)
                                                   at com.yanzhenjie.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:104)

**Comment by yanzhenjie** [comment]
请贴一下你的代码。

**Comment by qiulei19850103** [comment]
请求的代码。基本上使用你demo的请求框架

**Comment by yanzhenjie** [comment]
请问下是在BaseActivity的onCreate中建立队列在onDestory总stop队列，然后提供方法，在子Activity中请求这样的吗？

**Comment by qiulei19850103** [comment]
请求队列是在一个单例类初始化创建的。在onDestory中只cancel掉request，退出应用时stop队列。

**Comment by yanzhenjie** [comment]
如果是使用队列的方式的话，建议你采用我上述做法来封装。新版本的demo也早就更新了这种方式了，单例的方式在低版本的手机上是会发生内存泄漏的。但是那种做法我认为不应该发生内存泄漏，而且在高版本手机上不存在，我怀疑是系统问题。所以如果使用队列请使用我上述方法来做。
